[package]
name = "opavs-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_yaml = "0.9"

[dependencies.opavs]
path = ".."

[[bin]]
name = "fuzz_import_yaml"
path = "fuzz_targets/fuzz_import_yaml.rs"
test = false
doc = false
bench = false
